### ISSUE TITLE
pcount support lists and count NA's in mixed type data.

### ISSUE THREAD

**Issue by SebKrantz** [2005m/kit#21]
Hi Morgan, I have another suggestion for `pcount`: It would be great if this function could be used to row-wise count missing values in mixed type data frames, e.g. `pcount(data, value = NA)`. If this can be implemented, I would even think about making `value = NA` the default, as this is likely to become a common application of the function.

**Comment by 2005m** [comment]
Hi, Please try the master branch with `pcount(df, value=NA_real_)` and let me know if any issue. An alternative option is to do `apply(df, 1, kit::countNA)`, but you might argue that it is not as fast.

**Comment by SebKrantz** [comment]
Thanks, that works well! It would of course be possible to implement this for mixed-type data, using `asReal`, `asInteger`, `asChar` etc. for a generic `value = NA`, but I understand that, as regards other values, you might prefer to keep the type mismatch error, and it could be tedious to do an exemption for NA's.

**Comment by 2005m** [comment]
Thank you. I will close the issue then. I will try to push these changes to CRAN as soon as I can. Probably during the weekend.

**Comment by Kamgang-B** [comment]
Hi Morgan

I know that this issue is closed but I suggest to consider @SebKrantz's suggestion about mixed-type for the particular case where `value=NA` in `pcount`.  

I think that `CpcountNAR` is quite special and should be less restrictive than other (rowwise) functions. Instead of requiring that all elements in a data.frame/list be of the same type, I suggest to relax the current restriction and require the elements to be *all atomic* (regardless of the class, and therefore including factors, etc.).

My typical use case on data.frame/list (and I think it is the same for others) would be `pcount(df, value=NA)` where df is a data.frame/list of atomic elements (often of various types: logical/integer/double/character but also factors, etc.). I think of `pcount(df, value=NA)` as an alternative for `rowSums(is.na(df))` when df is a data.frame of only atomic columns.

I also suggest to export `CpcountNAR` (as `pcountNA`) just like `count` and `countNA`. I find `pcountNA(df)` more convenient, nicer and straightforward than `pcount(df, value=NA)`.

Thanks for all your effort!

**Comment by 2005m** [comment]
Hi guys,
Can you please have a look at the pull request I just opened and let me know what you think?
I really did it quick so I expected to have missed a lot of things.
Thank you
Kind regards.

**Comment by Kamgang-B** [comment]
Hi Morgan,

Hope you are fine!

Sorry for my very late reply but I was very busy.

Here are some issues that I identified.


	a = data.frame(x=1:3, y=Sys.Date()+c(NA,1:2))
	a
	  x          y
	1 1       <NA>
	2 2 2022-05-31
	3 3 2022-06-01
	pcountNA(a)                        # OK
	[1] 1 0 0


	# change y to POSIXlt
	b = a
	b$y = as.POSIXlt(a$y)
	b
	  x          y
	1 1       <NA>
	2 2 2022-05-31
	3 3 2022-06-01
	pcountNA(b)                        
	Error in pcountNA(b) : 
	  Argument 2 is of length 9 but argument 1 is of length 3. If you wish to 'recycle' your argument, please use rep() to make this intent clear to the readers of your code.

 I expected `pcountNA` to handle POSIXlt object correctly possibly as an exception to the all-elements should be atomic rule I mentioned in my comment above [here](https://github.com/2005m/kit/issues/21#issuecomment-1107425313)

	d = b[1:9,]
	d
		  x          y
	1     1       <NA>
	2     2 2022-05-31
	3     3 2022-06-01
	NA   NA       <NA>
	NA.1 NA       <NA>
	NA.2 NA       <NA>
	NA.3 NA       <NA>
	NA.4 NA       <NA>
	NA.5 NA       <NA>
	pcountNA(d)                                  # unexpected since d$y is still a POSIXlt object
	[1] 0 0 0 1 1 1 1 1 1

	e = data.frame(x=1:3)
	e$y = list(NA, 1:2, 1)    
	e
	  x    y
	1 1   NA
	2 2 1, 2
	3 3    1
	pcountNA(e)                     # 1-I expected an error since e$y is a list
	[1] 0 0 0


As I said [here](https://github.com/2005m/kit/issues/21#issuecomment-1107425313), I suggest that `pcountNA` supports only a list of atomic elements. It would be nice to deviate from this rule only in cases where it's really necessary to avoid unexpected results like with objects of class `POSIXlt`, which are internally a `list` iirc.

Regards
